# -*- coding: utf-8 -*-
"""suicidios_colombia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rck3wAm_3ofjq_osz5xON8yX0uxzEjfw

##Suicidios Colombia Historico
"""

import pandas as pd
import numpy as np

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.rc('figure', figsize = (14,6))

import seaborn as sns

datos = pd.read_html('https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/colombia')
datos[0]

datos = datos[0]

datos.describe()

datos['Suicidio_año'] = datos.Suicidios/365

datos.head()

for valor in datos['Suicidios hombres']:
  if valor >= 1.0:
    datos['Suicidios hombres'] = datos['Suicidios hombres'].replace([valor],valor*1000)

for valor in datos['Suicidios']:
  datos['Suicidios'] = datos['Suicidios'].replace([valor],valor*1000)

datos.head()

datos['Suicidio_año'] = (datos.Suicidios/365).round(2)

datos.head()

for valor in datos['Suicidios tasa femenina']:
  datos['Suicidios tasa femenina'] = datos['Suicidios tasa femenina'].replace([valor], valor/100)

for valor in datos['Suicidios tasa masculina']:
  datos['Suicidios tasa masculina'] = datos['Suicidios tasa masculina'].replace([valor], valor/100)

for valor in datos['Suicidios por 100.000']:
  datos['Suicidios por 100.000'] = datos['Suicidios por 100.000'].replace([valor], valor/100)

datos.head()



"""##Analisis Estadistico"""

sns.catplot(x = 'Fecha', y = 'Suicidio_año', data = datos[datos['Fecha'] >= 2010], aspect = 3)
plt.title('Suicidios Ultima Decada', fontsize = 15)

sns.barplot(x = 'Fecha', y = 'Suicidio_año', data = datos[datos['Fecha'] >= 2010], palette= "rocket")
plt.title('Suicidios Diarios', fontsize = 15)

sns.barplot(x = 'Fecha', y = 'Suicidios', data = datos[datos['Fecha'] >= 2010], palette= "light:b")
plt.title('Suicidios Totales', fontsize = 15)

hombres_vs_mujeres = datos.groupby('Fecha')

hombres_vs_mujeres.groups

hombres_vs_mujeres = datos[['Fecha','Suicidios hombres', 'Suicidios mujeres']]
hombres_vs_mujeres

hombres_vs_mujeres=hombres_vs_mujeres[hombres_vs_mujeres['Fecha'] >= 2010]

hombres = hombres_vs_mujeres['Suicidios hombres'].values
hombres

hombres = ([   2340.,    2356.,    2203.,    2033.,    1863.,    1764.,
       1669.,    1739., 1669.,    1720.])
hombres = np.array(hombres)
hombres

mujeres = hombres_vs_mujeres['Suicidios mujeres'].values
mujeres
etiquetas = hombres_vs_mujeres['Fecha'].values

co = np.arange(len(hombres))
an = 0.30

fig, ax = plt.subplots()
ax.bar(co-an/2,hombres,an, label = 'Hombres')
ax.bar(co + an/2,mujeres,an, label = 'Mujeres', color = 'lightblue')
ax.set_title('Suicidios Hombres Vs Mujeres')
ax.set_xticks(co)
ax.set_xticklabels(etiquetas)
plt.legend()

data1 = pd.read_excel('suicidios.xlsx')
sns.lineplot(data = data1, x = 'Fecha', y='Suicidios hombres', label = 'Hombres')
sns.lineplot(data = data1, x = 'Fecha', y='Suicidios mujeres', label = 'Mujeres')
plt.xlabel('Year')
plt.ylabel('Suicides')
plt.title('Suicidios Hombres Vs Mujeres', fontsize = 15)

data1.head()

data1 = data1.rename(columns = {'Suicidios por 100.000':'Suicidios_año'})

type(data1.Suicidios_año[0])

data1 = pd.read_excel('suicidios.xlsx')
sns.lineplot(data = data1, x = 'Fecha', y='Suicidios', label = 'Suicidios')
plt.xlabel('Year')
plt.ylabel('Suicides')
plt.title('Total Suicidios', fontsize = 15)

valores = np.array([data1['Suicidios hombres'].sum(), data1['Suicidios mujeres'].sum()])
label = ('Hombres', 'Mujeres')

plt.pie(valores, labels = label, autopct='%1.1f%%', explode = (.1,.1), colors = ['lightblue','salmon'])
plt.title('Total Suicidios por Genero', fontsize = 15)

suicidios_m_10 = (((datos.iloc[0,1]/datos.iloc[9,1])*100)-100).round(2)

datos.iloc[0,1]

datos.iloc[9,1]

suicidios_h_10 = (((datos.iloc[0,2]/datos.iloc[9,2])-1)*100).round(2)

suicidios_10 = (((datos.iloc[0,3]/datos.iloc[9,3])*100)-100).round(2)

tasa_general = datos.iloc[0,6]
tasa_general

tasa_hombres = datos.iloc[0,5]

tasa_mujeres = datos.iloc[0, 4]

print('En la ultima decada el numero de suicidios de las mujeres presento un aumento del {} %'.format(suicidios_m_10))
print('En la ultima decada el numero de suicidios para los hombre presento un aumento del {} %'.format(suicidios_h_10))
print('En la ultima decada el numero de suicidios presento un aumento del {} %'.format(suicidios_10))

print('la tasa de suicidios en Colombia es de {} por cada 100.000 habitantes'.format(tasa_general))
print('la tasa de suicidios en Colombia para la poblacion masculina es de {} por cada 100.000 hombres'.format(tasa_hombres))
print('la tasa de suicidios en Colombia para la poblacion femenina es de {} por cada 100.000 mujeres'.format(tasa_mujeres))

